### PR TITLE
chore: update deps and test in Node v4/6/8

### PR DESCRIPTION
**Pull request by teppeis**
- [fs-promise is deprecated](https://github.com/kevinbeaty/fs-promise) and replaced with fs-extra

### CODE REVIEW

**Comment by teppeis** [comment]
axios@0.13 breaks:
- adapter signature: https://github.com/mzabriskie/axios/pull/372
- default headers and it changes digest and breaks tests

**Comment by teppeis** [comment]
Some tests failed but they depend on `http://jsonplaceholder.typicode.com/`'s condition.
Please retry.
It would be replaced with mock server like `nock`.

**Comment by nettofarah** [comment]
Hey, @teppeis.
Thanks for starting the work here.

Two things I would like to address:

1) Can you make sure the code you write supports both interceptor signatures?
I would hate to have this lib break for people that currently rely on axios-vcr.

2) as for using something like `nock`. I feel that it would kind of defeat the purpose of what we're trying to test with axios-vcr. Testing a mock generator with another mock seems a bit weird IMO.

**Comment by nettofarah** [comment]
Closing this in favor of #4

**Comment by teppeis** [comment]
@nettofarah thanks!

**Pull request closed without merging**
